# Generated by Django 5.0.7 on 2024-08-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duración del quiz en minutos')),
                ('required_score_to_pass', models.IntegerField(help_text='puntaje requerido en %')),
                ('difficulty', models.CharField(choices=[('facil', 'facil'), ('medio', 'medio'), ('dificil', 'dificil')], max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
